baseURL = 'https://hacdan.org/'
languageCode = 'en-us'
title = 'hacdan.org'
theme = 'hello-friend-ng'
paginate = 10

googleAnalytics = "UA-78885046-1"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

enableRobotsTXT = true
enableGitInfo = false

[author]
  name = "David McClellan"

[[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/posts"
[[menu.main]]
  identifier = "resume"
  name = "Resume"
  url = "/resume/readme/"

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
 
  [params.favicon.color]
    mask = "#ffffff"
    msapplicaiton = "#ffffff"
    theme = "ffffff"
    
  [params.footer]
    trademark = false
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
    ]
  [params.logo]
    logoMark     = "#"
    logoText     = "> cd /Users/HacDan/"
    logoHomeLink = "/"
    logoCursorColor = "#67A2C9"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/_hacdan"


  [[params.social]]
    name = "github"
    url = "https://github.com/hacdan"
