baseURL = 'https://hacdan.org/'
languageCode = 'en-us'
title = 'hacdan.org'
theme = 'hello-friend-ng'
paginate = 10

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
